name: "Build game"
on: [push]
env:
  GODOT_VERSION: 3.3
jobs:
  export-web:
    name: Web Export ğŸŒ
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:mono-${GODOT_VERSION}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup ğŸ’»
        run: |
          mkdir -v -p build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build ğŸ”§
        run: godot -v --export "HTML5" ./build/web/index.html
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: |
            build/web/**
  export-desktop:
    name: Generate releases ğŸ—”
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:mono-${GODOT_VERSION}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup ğŸ’»
        run: |
          mkdir -v -p build/windows build/linux build/macosx ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Generate Documentation
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "material_maker/doc"
      - name: Windows Build ğŸ—”
        run: godot -v --export "Windows" ./build/windows/LinwoodWorld.exe
      - name: Linux Build ğŸ§
        run: godot -v --export "Linux/X11" ./build/linux/LinwoodWorld.x86_64
      - name: Mac OSX Build ğŸ§
        run: godot -v --export "Mac OSX" ./build/macosx.zip
      - name: Unzip Mac OSX build ğŸ“
        run: |
          cd build
          unzip macosx.zip
      - name: Upload Windows Artifact ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows
      - name: Upload Linux Artifact ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: build/linux
      - name: Upload Mac OSX Artifact ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: macosx-build
          path: build/macosx.zip
  publish:
    name: â¬† Publish  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy preview ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: github.ref == 'refs/heads/develop'
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: web-build # The folder the action should deploy.
          target-folder: preview
      - name: Deploy release ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
